# Generated by Django 4.2.9 on 2024-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('board', models.CharField(max_length=200)),
                ('creator_name', models.CharField(max_length=30)),
                ('player2', models.CharField(max_length=30)),
            ],
        ),
    ]
