# Generated by Django 4.2.9 on 2024-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isGuest',
            field=models.BooleanField(default=False),
        ),
    ]
