# Generated by Django 4.2.9 on 2024-02-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_game_id_game_creator_cards_game_player_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(choices=[(1, 'Player 1'), (2, 'Player 2')], default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(blank=True, default=None, max_length=169, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator_cards',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_cards',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
