# Generated by Django 4.2.9 on 2024-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_game_turn_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
    ]
