# Generated by Django 4.2.9 on 2024-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game_creator_score_game_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lastMove',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
