# Generated by Django 4.2.9 on 2024-11-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_lastmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='command',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
